#!/bin/bash

# set defaults
basename=$PWD/../../
num_slave_procs=1
num_slave_tasks=1
ioeng_mem=1024
master_mem=1024
slave_mem=256

while test $# -gt 0; do
   case "$1" in
      -h|--help)
         echo "help option specified"
         exit 1
         ;;
      -b)
         shift
         if test $# -gt 0; then
            basename=$1
         else
            echo "no base directory specified"
            exit 1
         fi
         shift
         ;;
      -num_procs)
         shift
         if test $# -gt 0; then
            num_slave_procs=$1
         else
            echo "number of slave processes not specified"
            exit 1
         fi
         shift
         ;;
      -num_tasks)
         shift
         if test $# -gt 0; then
            num_slave_tasks=$1
         else
            echo "number of slave tasks not specified"
            exit 1
         fi
         shift
         ;;
      -parameters)
         shift
         if test $# -gt 0; then
            parameters=$1
         else
            echo ""
            exit 1
         fi
         shift
         ;;
      -ioeng_mem)
         shift
         if test $# -gt 0; then
            ioeng_mem=$1
         else
            echo ""
            exit 1
         fi
         shift
         ;;
      -master_mem)
         shift
         if test $# -gt 0; then
            master_mem=$1
         else
            echo ""
            exit 1
         fi
         shift
         ;;
      -slave_mem)
         shift
         if test $# -gt 0; then
            slave_mem=$1
         else
            echo ""
            exit 1
         fi
         shift
         ;;
      *)
         shift
         ;;
   esac
done

# export parameters file to the environment variables
export GPNC_PARAMS=$parameters

# export number of slave processes to the environment variables
export GPNC_NUM_SLAVE_PROCS=$num_slave_procs

# export number of slave tasks to the environment variables
export GPNC_NUM_SLAVE_TASKS=$num_slave_tasks

# export IO engine memory size
export GPNC_IOENG_MEM=$ioeng_mem

# export master process memory size
export GPNC_MASTER_MEM=$master_mem

# export slave process memory size
export GPNC_SLAVE_MEM=$slave_mem

# xterm -e gdb -q -tui 

# mpirun                              \
$HOME/user_libs/openmpi_3p0p0/bin/mpirun -oversubscribe   \
       -n 1 $basename/ioeng/ioexe : \
       -n 1 $basename/main/master : \
       -n $num_slave_procs $basename/main/slave
