#!/bin/bash

$HOME/user_libs/openmpi/bin/mpirun   \
   --mca orte_base_help_aggregate 0  \
   -oversubscribe                    \
   -n 1 module_0.exe :               \
   -n 1 module_1.exe :               \
   -n 2 module_2.exe :               \
   -n 6 module_3.exe :               \
#
