#!/bin/bash

basedir=$PWD/../../
ioexe=$basedir/ioeng/ioexe
master=$basedir/main/master
slave=$basedir/main/slave
parameters=$basedir/main/run/parameters.txt

../../gpnc_tools/submit_scripts/submit  \
   -ioexe  $ioexe                       \
   -master $master                      \
   -slave  $slave                       \
   -num_procs 2                         \
   -num_tasks 3                         \
   -ioeng_mem 2048                      \
   -master_mem 2048                     \
   -slave_mem 2048                      \
   -parameters $parameters              \
#
